version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-local
    ports:
      - 15672:15672
      - 5672:5672
      - 5671:5671
    environment:
      - RABBITMQ_DEFAULT_USER=guest 
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
        - rabbitmq-volume:/var
    networks:
        - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge
volumes:
  rabbitmq-volume:
    external: false